.travis.yml
CMakeLists.txt
README.md
build.ps1
debian/control
debian/rules
etc/Doxyfile.in
libdigidocpp.dox

- move index.dox to parent folder and rename to libdigidocpp.dox
- remove obsolete INSTALL_DOC cmake parameter, installation can be disabled with cmake parameter -DDOXYGEN_EXECUTABLE=""
- remove download references form build instructions, they are downloaded with prepare_win_build_environment.ps1 script

Doc updates

---

etc/schema/XAdES01903v132-201601.xsd
libdigidocpp.dox
src/SignatureBES.cpp
src/xml/AnyType.cpp
src/xml/AnyType.h

- Handle ClaimedRole as AnyType
- Reverts back to standard schema and resolve string handling custom AnyType c++ class
Only affects schema validation (bdoc is still created with string only)
SKEID-73
Signed-off-by: Raul Metsma raul@metsma.ee

Compatibility with Lithuanian ADoc 1.0 documents

---

etc/schema/XAdES01903v132-201601-relaxed.xsd
src/BDoc.cpp
src/CMakeLists.txt
src/SignatureA.cpp
src/SignatureA.h
src/SignatureBES.cpp
src/SignatureBES.h
src/SignatureTM.cpp
src/SignatureTM.h
src/SignatureTS.cpp
src/SignatureTS.h

IB-4432: Relax the validation of BDOC container's signature XML:
allow sub-elements of element SignatureProductionPlace in any order (xsd:sequence -> xsd:all).
Dedicated XSD file XAdES01903v132-201601-relaxed.xsd created which is used to validate
the BDOC containers which are created externally.
New constructors added for Signature* classes in order to retain ABI compatibility.

Relax the validation of external BDOC Signat. XML

---

src/BDoc.cpp
src/util/ZipSerialize.cpp

If file can not be loaded to memory the error is returned:
Failed to write file ... data to stream. Stream size: ...
META-INF/manifest.xml file size is not limited. It could be as big as
application/system can handle.
Signed-off-by: Oleg Prokofjev oleg@aktors.ee

IB-3793 double click on ZIP-bomb BDOC should not crash

---

src/crypto/OCSP.cpp
src/crypto/OCSP.h

- Remove outdated comments
- Use shared pointer to enable C++11 move semantics
- Use RVO patterns

Cleanup OCSP class

---

src/SignatureTS.cpp

removed "TimeStamp have to be after OCSP response" condition on validation
removed "TimeStamp time and OCSP producedAt have to be within 24h" condition on validation
(security risks raised as the Estonian eID certificates' validity can be suspended temporarily and activated later additional analysis recomended)
SKEID-93
Signed-off-by: Raul Metsma raul@metsma.ee
Recreated open-eid/libdigidocpp#10

Compatibility with Latvian ASiC-E documents

---

src/crypto/TSL.cpp
src/crypto/TSL.h
src/util/DateTime.cpp
src/util/DateTime.h
test/libdigidocpp_boost.cpp

IB-4224: Use HTTP header "Last-Modified" for checking if TSL is updated when
sha2 digest does not exist. If checksum is not present, fetch headers and check
if cached timestamp matches remote "Last-Modified" header.
Download whole TSL if timestamp does not match or timestamp is not cached.

Use HTTP header "Last-Modified" for TSL check

---

src/crypto/OCSP.cpp

'SecKeychainItemExport' is deprecated: first deprecated in macOS 10.7

Fix warning

---

test/CMakeLists.txt

Work-around for failing unit tests with Boost.test 1.62 - issue https://svn.boost.org/trac/boost/ticket/12507
(default ver. on Ubuntu 17.04).

Boost.test 1.62 --log_sink work-around (Ubuntu 17.04)

---

src/crypto/X509Crypto.cpp
test/libdigidocpp_boost.cpp

Fix escaped UTF-8 characters

---

AUTHORS

In [libdigidocpp Fedora package review](https://bugzilla.redhat.com/show_bug.cgi?id=1519747) reviewer Robert-André Mauchin found out that AUTHORS file encoding is ISO-8859-1 instead of UTF-8, so [I used iconv to convert it](https://fedoraproject.org/wiki/Packaging_tricks#Convert_encoding_to_UTF-8)

Converted AUTHORS encoding from ISO-8859-1 to UTF-8

---

COPYING

In [libdigidocpp Fedora package review](https://bugzilla.redhat.com/show_bug.cgi?id=1519749) reviewer Robert-André Mauchin found out that COPYING file encoding is ISO-8859-1 instead of UTF-8, so [I used iconv to convert it](https://fedoraproject.org/wiki/Packaging_tricks#Convert_encoding_to_UTF-8)

Converted COPYING encoding from ISO-8859-1 to UTF-8

---

src/util/ZipSerialize.cpp

Use case sensitive file compare and c++11 formating

---

src/crypto/TSL.cpp

Validate TSL SHA file only when ETag is not available

---

src/jsonxx.cc
src/jsonxx.h

Inconsistent definition of copy constructor and assignment ('Rule of Two')
IB-5912

Fix LGTM warning

---

prepare_osx_build_environment.sh
src/SignatureXAdES_B.cpp
src/SignatureXAdES_LTA.cpp
src/crypto/TSL.cpp

Workaround macOS hiding xml-security symbols

---

src/ASiC_E.cpp
src/ASiC_E.h
src/ASiContainer.cpp
src/ASiContainer.h
test/libdigidocpp_boost.cpp

- don't allow filename 'mimetype'
- don't allow filename with path
- check mediatype format
Fixes #375, IB-6708

AddDataFile checks

---

.github/workflows/build.yml
src/crypto/X509CertStore.cpp

Handle NO TSA certificates

---

.github/workflows/build.yml
build-library.sh
prepare_osx_build_environment.sh
src/crypto/TS.cpp

Upgrade openssl 1.1.1m and fix crash with new openssl version

---

src/XmlConf.cpp

Fix parameter locking when false is defined

---

src/SignatureXAdES_B.cpp
src/SignatureXAdES_T.cpp
src/xml/UnsignedSignaturePropertiesType.cpp
src/xml/UnsignedSignaturePropertiesType.h

Allow validate signatures with TimeStampValidationData

---

src/CMakeLists.txt

No need to configure digidoc-tool(1) if the program is not compiled.
Signed-off-by: Klemens Nanni <klemens@posteo.de>

Build manual page conditionally

---

src/digidoc-tool.1.cmake

On Linux and BSD, the macOS default is certainly wrong.
Use the variable populated by CMake to reflect the actually used path
in the manual.
This properly shows the following on OpenBSD:
--pkcs11[=]    - default is /usr/local/lib/pkcs11/opensc-pkcs11.so. Path of PKCS11 driver.
Signed-off-by: Klemens Nanni <klemens@posteo.de>

digidoc-tool.1: Use actual PKCS11 module path

---

src/crypto/Digest.cpp
src/crypto/OpenSSLHelpers.h
src/crypto/TS.cpp
src/crypto/X509Cert.cpp
src/crypto/X509Crypto.cpp

With the upcoming 3.6 release LibreSSL will ship
`X509_VERIFY_PARAM_get_time()` as required by libdigidocpp.
Furthermore, the following changes are required to build latest HEAD against
current LibreSSL:
- Omit SHA3 with LibreSSL
- Omit BIO_F_BIO_LOOKUP_EX handling with LibreSSL
- Provide OPENSSL_memdup() and TS accessors with LibreSSL
- Use old-style STACK_OF stuff for LibreSSL
- Do not define ESS_ISSUER_SERIAL with LibreSSL
All patches patches were written by @botovq against the 3.14.8 release during
review of my OpenBSD ports/package submission for libdigidocpp[0].
I rebased the patches onto latest HEAD (d9fd053) and retested on
OpenBSD/amd64 7.1 -CURRENT, i.e. today's latest LibreSSL development version.
0: https://github.com/openbsd/ports/commit/a015763b93d663421e15e7f233ae3ee7ed89b8c …

Fix building against LibreSSL

---

src/SiVaContainer.cpp
src/SiVaContainer.h
src/xml/SecureDOMParser.cpp
src/xml/SecureDOMParser.h

Optimize DDoc memory handling

---

COPYING
etc/schema/OpenDocument_manifest_v1_2.xsd
src/ASiC_E.cpp
src/ASiC_S.cpp
src/ASiContainer.cpp
src/ASiContainer.h
src/CMakeLists.txt

Create manifest as version 1.2 and validate 1.0 to keep backward compatibility

---

.github/workflows/build.yml
etc/digidocpp.conf.cmake
src/Conf.cpp
src/util/File.cpp
src/util/File.h

Remove old config leftovers and optimize env checks

---

.gitattributes
RELEASE-NOTES.md
patches/README.md
patches/vcpkg-ports/xalan-c/fix-linux-no-bin.patch
patches/vcpkg-ports/xalan-c/fix-missing-dll-error.patch
patches/vcpkg-ports/xalan-c/fix-win-deprecated-err.patch
patches/vcpkg-ports/xalan-c/portfile.cmake
patches/vcpkg-ports/xalan-c/vcpkg.json

Make copy of xalan-c port

---

src/crypto/TS.cpp
src/crypto/X509Crypto.cpp

See LibreSSL 3.6.0 (October 5th, 2022) changelog:
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.6.0-relnotes.txt
Courtesy of Theo Buehler < tb AT openbsd DOT org>, who provided these
fixes as local ports patches;  I merely upstream them.

LibreSSL: opaque TS structs, 3.6.0 provides TS accessors

---

src/minizip/ioapi.c
src/minizip/ioapi.h
src/minizip/iowin32.c
src/minizip/unzip.c
src/minizip/unzip.h
src/minizip/zip.c
src/minizip/zip.h
src/util/ZipSerialize.cpp

https://github.com/madler/zlib/releases/tag/v1.2.13
Noticed by building libdigidocpp 3.14.11 on OpenBSD where we still have
to pass `CFLAGS += -DIOAPI_NO_64` as off_t is always 64-bit.
1.2.13 contains a fix for this but libdigidocpp would fail to build, i.e.
it still ships an old version.

Update to minizip 1.2.13

---

src/Conf.cpp
src/Conf.h
src/Exports.h
src/XmlConf.cpp
src/XmlConf.h
src/crypto/OpenSSLHelpers.h
src/crypto/PKCS11Signer.cpp
src/crypto/TS.cpp
src/crypto/TS.h
src/crypto/X509Cert.cpp
src/crypto/X509Cert.h
test/libdigidocpp_boost.cpp

Add option to verify TS service certificate

---

.github/workflows/build.yml
README.md
build-library.sh
build.ps1
debian/rules
patches/vcpkg-ports/xerces-c/disable-tests.patch
patches/vcpkg-ports/xerces-c/portfile.cmake
patches/vcpkg-ports/xerces-c/remove-dll-export-macro.patch
patches/vcpkg-ports/xerces-c/usage
patches/vcpkg-ports/xerces-c/vcpkg-cmake-wrapper.cmake
patches/vcpkg-ports/xerces-c/vcpkg.json
src/ASiContainer.cpp
src/ASiContainer.h
src/Conf.cpp
src/SiVaContainer.cpp
src/XmlConf.cpp
src/crypto/TSL.cpp
src/crypto/X509CertStore.cpp
src/util/File.cpp
src/util/File.h
test/CMakeLists.txt
test/data/digidocpp.conf
test/libdigidocpp_boost.cpp

Use Github Actions CodeQL tests

---

libdigidocpp.wxs
src/CMakeLists.txt
src/digidoc-tool.cpp
src/libdigidocpp.i.h
src/libdigidocpp.rc

- add version info to swig bindings
- include manifest 1.2 schema
IB-7392

Workaround MSVC 2019 issue

---

src/SignatureXAdES_B.cpp
src/SignatureXAdES_B.h
src/SignatureXAdES_T.cpp

Implement CompleteRevocationsRefs check

---

etc/Doxyfile.css
etc/Doxyfile.in
src/Conf.cpp
src/Container.cpp
src/Exception.cpp
src/Signature.cpp
src/XmlConf.cpp

Improve documentation

---

.github/workflows/build.yml
src/crypto/Connect.cpp

Check if cert is valid

---

README.md
RELEASE-NOTES.md
src/SignatureXAdES_LT.cpp
src/crypto/OCSP.cpp
src/crypto/OCSP.h

Send 32 byte nonce with TS profile

---

prepare_osx_build_environment.sh

OpenSSL engines support is needed

---

.github/workflows/build.yml
patches/vcpkg-ports/openssl/portfile.cmake
patches/vcpkg-ports/openssl/unix/configure
patches/vcpkg-ports/openssl/vcpkg.json
patches/vcpkg-ports/openssl/windows/portfile.cmake
src/crypto/TS.cpp
src/crypto/X509CertStore.cpp
vcpkg.json

Update OpenSSL 3.0.10

---

src/crypto/Digest.h

From <openssl/evp.h> aka. EVP_Digest(3), otherwise OpenBSD builds fail:
```
/usr/include/openssl/ossl_typ.h:103:30: error: type alias redefinition with different types ('struct env_md_ctx_st' vs 'struct evp_md_ctx_st')
typedef struct env_md_ctx_st EVP_MD_CTX;
^
/usr/ports/pobj/libdigidocpp-3.16.0/libdigidocpp-3.16.0/src/crypto/Digest.h:59:7: note: previous definition is here
using EVP_MD_CTX = struct evp_md_ctx_st;
```
As metsma@ advised, don't include the OpenSSL header in this header to
so as not to introduce build time dependencies to third party usages.
Signed-off-by: Klemens Nanni <kn@openbsd.org>

Fix EVP_MD_CTX type definition for LibreSSL

---

.github/workflows/build.yml
src/minizip/MiniZip64_Changes.txt
src/minizip/ioapi.c
src/minizip/ioapi.h
src/minizip/iowin32.c
src/minizip/iowin32.h
src/minizip/unzip.c
src/minizip/unzip.h
src/minizip/zip.c
src/minizip/zip.h
vcpkg.json

Update zlib&minizip dependencies

---

src/ASiC_S.cpp
src/ASiC_S.h
src/ASiContainer.cpp
src/ASiContainer.h
src/SignatureTST.cpp
src/SignatureTST.h
src/SignatureXAdES_B.cpp
src/crypto/X509Crypto.cpp
src/crypto/X509Crypto.h
src/util/ZipSerialize.cpp

Handle ASiC-S XAdES signatures

---

src/crypto/X509Crypto.cpp

Fix issuer name compare

---

src/XmlConf.cpp

Don't throw when setting value and config is empty

---

.github/workflows/build.yml
src/ASiContainer.cpp
src/ASiContainer.h
src/SiVaContainer.cpp
src/SiVaContainer.h

Validate CAdES signature in SiVa service

---

prepare_win_build_environment.ps1

Use XSD 4.2.0

---

src/SiVaContainer.cpp

Ask SiVa confirmation only once

---

.github/workflows/build.yml
CMakeLists.txt
src/util/ZipSerialize.cpp

Fedora has switched to `minizip-ng` (with the compat mode) and these patches fixed the failed build of `libdigidocpp`.
You can see more here: https://src.fedoraproject.org/rpms/libdigidocpp/pull-request/4
Signed-off-by: Lukas Javorsky <ljavorsk@redhat.com>

Support minizip-ng build

---

src/SignatureXAdES_B.cpp
src/SignatureXAdES_B.h
src/xml/SecureDOMParser.cpp

Use XML-C14N as fallback Canonical method

---

src/SignatureXAdES_B.cpp
src/SignatureXAdES_B.h
src/SignatureXAdES_LT.cpp
src/SignatureXAdES_T.cpp
src/crypto/Connect.cpp
src/crypto/PKCS11Signer.cpp
src/crypto/TSL.cpp
src/digidoc-tool.cpp
src/util/File.cpp
src/util/File.h

Fix coverity warnings

---

.github/workflows/build.yml
prepare_win_build_environment.ps1

Fix build using fixed WIX extension version

---

src/crypto/Connect.cpp
src/crypto/Connect.h
src/crypto/TSL.cpp
src/crypto/TSL.h
src/crypto/X509CertStore.cpp

Simplify TSL parsing

---

src/util/File.cpp

Fix return  vale on error

---

src/Container.cpp
src/XMLDocument.h

Allow to set empty content to node and remove deprecated api usage

---

etc/schema/OpenDocument_dsig.xsd
src/ASiC_E.cpp
src/SiVaContainer.cpp
src/SignatureXAdES_B.cpp
src/SignatureXAdES_B.h
src/SignatureXAdES_LT.cpp
src/SignatureXAdES_LTA.cpp
src/SignatureXAdES_T.cpp
src/SignatureXAdES_T.h
src/XMLDocument.h
src/XmlConf.cpp
src/crypto/Connect.cpp
src/crypto/Connect.h
src/crypto/TSL.cpp
src/crypto/TSL.h

Implement LTA support

---

examples/DigiDocCSharp/DigiDocCSharp.csproj
examples/DigiDocCSharp/Program.cs
examples/java/src/main/java/ee/ria/libdigidocpp/libdigidocpp.java
libdigidocpp.i
src/CMakeLists.txt

Fix C# memory leaks and handle X509Cert as native type where possible

---

src/ASiContainer.cpp
src/ASiContainer.h

Don't allow to sign empty file

---

src/ASiC_E.cpp
src/ASiC_E.h
src/ASiC_S.cpp
src/ASiC_S.h
src/ASiContainer.cpp
src/ASiContainer.h
src/SiVaContainer.cpp
src/SignatureTST.cpp
src/SignatureTST.h
src/util/ZipSerialize.cpp
src/util/ZipSerialize.h

Check duplicate files in Zip all code paths

---

src/crypto/OCSP.cpp

Fix crash when OCSP_RESPONSE does not contain OCSP_BASIC_RESPONSE

---

.github/workflows/build.yml
README.md

Some Fedora-related housekeeping due to upcoming Fedora 41 release:
Firstly, include `cmake` submodule using full repository url, which allows running Github actions without hardcoded relative repository locations.
And second and somewhat more controversial change would be the inclusion of `rawhide` in the Fedora build matrix. If there are objections, this could be dropped.

Misc Fedora-related improvements

---

.github/workflows/build.yml
src/crypto/TSL.cpp
src/crypto/X509CertStore.cpp
test/data/EE_T-CA-invalid-type.xml
test/data/EE_T-CA-non-qa.xml
test/data/EE_T-CA-withdrawn-granted-before.xml
test/data/EE_T-CA-withdrawn-granted-later.xml
test/data/EE_T-CA-withdrawn.xml
test/data/EE_T-OCSP-invalid-type.xml
test/data/EE_T-OCSP-withdrawn-granted-before.xml
test/data/EE_T-OCSP-withdrawn-granted-later.xml
test/data/EE_T-OCSP-withdrawn.xml
test/data/EE_T-TSA-invalid-type.xml
test/data/EE_T-TSA-withdrawn-granted-before.xml
test/data/EE_T-TSA-withdrawn-granted-later.xml
test/data/EE_T-TSA-withdrawn.xml
test/data/EE_T-no_QCSD.xml
test/data/EE_T-no_QCStatement.xml
test/data/EE_T.xml

Allow only qualified TimeStamp-s

---

.github/workflows/build.yml
README.md
build.ps1
libdigidocpp.wxs
src/CMakeLists.txt

Add Windows Arm64 build

---

src/ASiC_E.cpp
src/ASiC_E.h
src/ASiC_S.cpp
src/ASiC_S.h
src/ASiContainer.cpp
src/ASiContainer.h
src/SiVaContainer.cpp
src/SignatureTST.cpp
src/SignatureTST.h
src/XMLDocument.h
src/XmlConf.cpp
src/util/ZipSerialize.cpp
src/util/ZipSerialize.h

IB-8290
Signed-off-by: Firstname Lastname <firstname.lastname@example.com>

ASiC-S TimeStamp save support

---

src/crypto/TSL.cpp
src/crypto/X509CertStore.cpp
src/util/algorithm.h
test/CMakeLists.txt
test/data/EE_T-CA-granted-later.xml
test/data/EE_T-CA-noqscd-granted-before.xml
test/data/EE_T-CA-noqscd-granted-later.xml
test/data/EE_T-OCSP-granted-later.xml
test/data/EE_T-OCSP-noqscd-granted-before.xml
test/data/EE_T-OCSP-noqscd-granted-later.xml
test/data/EE_T-TSA-granted-later.xml
test/data/EE_T-TSA-noqscd-granted-before.xml
test/data/EE_T-TSA-noqscd-granted-later.xml
test/test.h

Allow only qualified OCSP-s 

---

src/SignatureTST.cpp
src/SignatureXAdES_T.cpp
src/XMLDocument.h
src/crypto/Connect.cpp
src/crypto/Digest.cpp
src/crypto/Digest.h
src/crypto/OCSP.cpp
src/crypto/OCSP.h
src/crypto/OpenSSLHelpers.h
src/crypto/TS.cpp
src/crypto/TS.h
src/crypto/X509CertStore.cpp
src/crypto/X509CertStore.h
src/util/DateTime.cpp
src/util/memory.h

Validate signing certificate on issue date and on TSA time

---

src/crypto/Connect.cpp
src/util/algorithm.h
src/util/memory.h

Handle proxy responses with case insensitive and OK result

---

src/CMakeLists.txt
src/digidoc-tool.cpp
src/digidoc-tool.manifest

Fix tool unicode usage in Windows

---

.github/workflows/build.yml

Build on Github Actions Linux ARM64 target

---

src/SignatureXAdES_B.cpp
src/SignatureXAdES_LT.cpp
src/SignatureXAdES_LTA.cpp
src/SignatureXAdES_T.cpp

Catch processing exceptions and add to list

---

.github/workflows/build.yml
src/XMLDocument.h
src/util/memory.h

Fix xmlNode clearing

---

src/crypto/PKCS11Signer.cpp

Logout PKCS11 session after successful sign and dont leak session

---

src/ASiC_S.cpp
src/ASiC_S.h
src/ASiContainer.cpp
src/ASiContainer.h
src/SignatureTST.cpp
src/SignatureTST.h
src/SignatureXAdES_B.cpp
src/SignatureXAdES_B.h
src/XMLDocument.h
src/crypto/TSL.cpp

Validate ASiC-S manifest containers

---

examples/DigiDocCSharp/Program.cs
examples/java/src/main/java/ee/ria/libdigidocpp/libdigidocpp.java
libdigidocpp.i
src/Signature.cpp
src/Signature.h
src/SignatureTST.cpp
src/SignatureTST.h
src/digidoc-tool.cpp

ASiC-S LTA extending support
