src/crypto/PKCS11Signer.cpp, src/digidoc-tool.cpp
=> createBatch command for signing entire folder

src/SignatureBES.cpp, src/digidoc-tool.cpp
without TimeStamp and Revocation info
=> Allow to create BES and EPES signatures

etc/digidocpp.conf.cmake, src/Conf.cpp
=> Add TEST of EID-SK 2011 OCSP URL

src/DDoc.cpp, src/RDoc.cpp, src/util/File.cpp, src/util/File.h
=> Add File::fileExtension method

.travis.yml, examples/libdigidocpp-android/build-library.sh
=> Travis: Build Android/iOS targets

CMakeLists.txt
=> Enable CMake policy CMP0063

src/crypto/OCSP.cpp, test/libdigidocpp_boost.cpp
=> Fix memory leak and use latest Config class

examples/libdigidocpp-ios/build-library.sh, prepare_osx_build_environment.sh
- libc++ is default
- print build steps
- increase iOS minimum 9.0
- increase OSX minimum 10.9
- install only android standalone toolchain when needed
=> Improve build script

.travis.yml
=> Speed up travis build, use ccache

etc/schema/en_31916201v010101.xsd, etc/schema/en_31916201v010101.xsd.orig, libdigidocpp.dox, libdigidocpp.wxs, src/CMakeLists.txt, src/SignatureBES.cpp
=> Update ASiC EN schema

etc/digidocpp.conf.cmake, libdigidocpp.dox
to make sure all latest parameters are listed
=> Include directly digidocpp.conf to doxygen

prepare_osx_build_environment.sh, prepare_win_build_environment.ps1
=> Update openssl to 1.0.2j

libdigidocpp.wxs
=> Commit e6f729c67d79da1fef003d12b6f9ef69b52e9622 forgot alter WIX installer project

.travis.yml, build.ps1, examples/libdigidocpp-android/build-library.sh, prepare_osx_build_environment.sh, prepare_win_build_environment.ps1
=> Build script improvements

libdigidocpp.dox, libdigidocpp.wxs
=> Add relaxed XaDES xsd to wix, update documentation

src/SignatureBES.cpp, src/SignatureBES.h, src/crypto/Signer.cpp, src/crypto/Signer.h, src/digidoc-tool.cpp
- API methods to create XAdES EN signature
- Tool parameters to create XAdES EN signature
SKEID-83
=> XAdES EN support

src/SignatureA.cpp, src/SignatureTM.cpp, src/SignatureTS.cpp, src/util/DateTime.cpp, src/util/DateTime.h
=> Add ASN1TimeToXSD method

prepare_win_build_environment.ps1
devenv does not upgrade toolchain when VS2013/2015 is installed paralel
=> Set VisualStudioVersion and PlatformToolset

etc/Doxyfile.in
=> Add hint to search example digidocpp.conf

prepare_osx_build_environment.sh
=> Update Android NDK 13

src/DDoc.cpp, src/DDoc.h, src/RDoc.h, src/Signature.cpp, src/Signature.h
=> Make streetAddress to non pure to fix ABI break and others also to cleanup

src/SignatureTM.cpp
similar to digidoc4j https://www.pivotaltracker.com/story/show/118546083
=> Set profile ASiC_E_BASELINE_LT_TM or ASiC_E_BASELINE_LT in OCSP useragent

src/ASiC_E.cpp, src/ASiC_E.h, src/CMakeLists.txt, src/Container.cpp, src/SignatureA.cpp, src/SignatureA.h, src/SignatureBES.cpp, src/SignatureBES.h, src/SignatureTM.cpp, src/SignatureTM.h, src/SignatureTS.cpp, src/SignatureTS.h
IB-4589 Refactoring of ASiC container related classes
-  BDoc -> ASiC_E
=> Refactor BDoc: change to ASiC_E

examples/libdigidocpp-android/xmlsec.patch, prepare_osx_build_environment.sh
=> Use latest xml-security-c on android/ios hosts

etc/Doxyfile.in, src/Container.cpp, src/Container.h
=> Minor documentation updates

etc/digidocpp.conf.cmake, src/Conf.cpp
=> Add new OCSP URL-s

.travis.yml
=> Build on ubuntu 16.04/16.10/16.04(32) docker image

prepare_osx_build_environment.sh, prepare_win_build_environment.ps1
=> Update zlib 1.2.11

examples/libdigidocpp-ios/libdigidocpp-ios.xcodeproj/project.pbxproj, examples/libdigidocpp-ios/libdigidocpp-ios/AppDelegate.mm, examples/libdigidocpp-ios/libdigidocpp-ios/Images.xcassets/AppIcon.appiconset/Contents.json
=> Update iOS example

src/Signature.cpp, src/Signature.h
=> Revert fixes ABI compatibility

src/util/DateTime.cpp
IB-4224: Use POSIX strptime() instead of C++ get_time() on Linux:
- space-padded date format (%e) does not work on Ubuntu
- get_time() is not available with GCC 4.8.4
=> Use strptime() instead of C++ get_time() on Linux

src/SignatureXAdES_LT.cpp, src/crypto/OCSP.cpp, src/crypto/TSL.cpp, src/crypto/TSL.h, src/crypto/X509CertStore.cpp, src/crypto/X509CertStore.h, test/CMakeLists.txt, test/data/README.md
=> Read qualified and non-qualified info from TSL

test/CMakeLists.txt
=> Fix build with DDoc enabled

src/crypto/OCSP.cpp
=> Fix OCSP validation without signer certificate

etc/schema/OpenDocument-v1.2-csd06-dsig-schema.rng, etc/schema/OpenDocument_dsig.xsd, libdigidocpp.wxs, src/CMakeLists.txt, src/SignatureXAdES_B.cpp, src/SignatureXAdES_B.h
- Handle ADoc 1.0 document-signatures root element
SKEID-63
Signed-off-by: Raul Metsma raul@metsma.ee
=> Compatibility with Lithuanian ADoc 1.0 documents

prepare_osx_build_environment.sh, prepare_win_build_environment.ps1
=> Update openssl 1.0.2k

prepare_win_build_environment.ps1, src/SignatureBES.cpp, src/SignatureTM.cpp, src/crypto/X509Cert.cpp, src/crypto/X509Cert.h, src/crypto/X509CertStore.cpp, src/crypto/X509CertStore.h
=> Verify signing certificate QCSD OID-s

etc/schema/ts_119612v020101_additionaltypes_xsd.xsd, etc/schema/ts_119612v020101_additionaltypes_xsd.xsd.orig, etc/schema/ts_119612v020101_sie_xsd.xsd, etc/schema/ts_119612v020101_sie_xsd.xsd.orig, src/CMakeLists.txt, src/crypto/TSL.cpp, src/crypto/TSL.h, src/crypto/X509Cert.cpp, src/crypto/X509Cert.h, src/crypto/X509CertStore.cpp, src/xml/ExtensionType.cpp, src/xml/ExtensionType.h, test/CMakeLists.txt, test/data/EE_T-no_QCSD.xml, test/data/EE_T-no_QCStatement.xml, test/data/README.md
=> Handle QCSD info from TSL and certificate

src/Signature.cpp, src/Signature.h, src/SignatureXAdES_B.cpp, src/SignatureXAdES_B.h, src/SignatureXAdES_LT.cpp, src/SignatureXAdES_LT.h, src/SignatureXAdES_LTA.cpp, src/SignatureXAdES_LTA.h, src/SignatureXAdES_T.cpp, src/SignatureXAdES_T.h, src/crypto/X509CertStore.cpp, src/crypto/X509CertStore.h, src/digidoc-tool.cpp
=> Option to give validation policy

.travis.yml, libdigidocpp.dox
=> Clean git folder before tar deploy

.travis.yml
=> Fix travis tag upload and read version number from project

.travis.yml
=> Enable AWS S3 build cache to speed up builds

examples/libdigidocpp-android/build-library.sh
=> Use armeabi-v7a

prepare_osx_build_environment.sh
=> Android NDK 14

prepare_osx_build_environment.sh, src/crypto/Connect.cpp, src/crypto/Digest.cpp, src/crypto/OCSP.cpp, src/crypto/PKCS12Signer.cpp, src/crypto/TS.cpp, src/crypto/X509Cert.cpp, src/crypto/X509CertStore.cpp, src/crypto/X509Crypto.cpp, xml-security-c-1.7.3_openssl1.1.patch
=> OpenSSL 1.1 support

src/crypto/Connect.cpp, src/crypto/OCSP.cpp, src/crypto/OpenSSLHelpers.h, src/crypto/TS.cpp, src/crypto/X509Cert.cpp
=> Use c++11 decltype

libdigidocpp.dox
=> Docs updated with overview of ASiC-S support

src/crypto/TS.cpp
=> Fix crash when accessing TS::time on null object and use C++11 RVO

src/SignatureXAdES_B.cpp
Related 2b3def7d7afe242ec346101b97ea29df0f9b8d71
=> Fix debug message “CommitmentTypeIndicationType is not supported”

src/crypto/X509Crypto.cpp, test/libdigidocpp_boost.cpp
=> Compare whole string

.travis.yml
=> Use latest Ubuntu 17.04, xcode 7.3 and run unit tests on linux

build.ps1
=> Use on signing sha256 timestamp

src/crypto/TS.cpp
=> Override smime_sign purpose bit because it is actually timestamp

etc/schema/XAdES01903v132-201601-relaxed.xsd
=> Relax xsd schema, to allow SignatureProductionPlace after SignerRole element

etc/digidocpp.conf.cmake, src/Conf.cpp
=> Add KLASS3-SK 2016 OCSP URL-s

src/SignatureXAdES_B.cpp, src/crypto/Signer.cpp, src/crypto/X509Crypto.cpp, src/crypto/X509Crypto.h, test/libdigidocpp_boost.cpp
=> Remove legacy hack

src/digidoc-tool.1.cmake, src/digidoc-tool.cpp
=> Add some colors to terminal output

src/SiVaContainer.cpp, src/SiVaContainer.h
=> Verify Policy URI and signatureLevel value

src/xml/AnyType.cpp
IB-4785 It should not depend on local macine's current code page.
Signed-off-by: Oleg Prokofjev <oleg@aktors.ee>
=> deliberately convert the string to UTF-8

.travis.yml
=> Fix coverity paths

.travis.yml
=> Run coverity under linux

build.ps1, libdigidocpp.wxs
=> Disable license

src/SignatureXAdES_LT.cpp
=> Restore compatibility with jdigidoc 3.11

src/SignatureXAdES_LT.cpp, src/SignatureXAdES_T.cpp, src/SignatureXAdES_T.h
=> Create UnsignedSignatureProperties when needed

CMakeLists.txt, RELEASE-NOTES.md
=> Add 3.13.1 changelog

.travis.yml, examples/libdigidocpp-android/README.md, examples/libdigidocpp-android/build-library.sh, examples/libdigidocpp-ios/README.md, examples/libdigidocpp-ios/build-library.sh, examples/libdigidocpp-ios/libdigidocpp-ios.xcodeproj/project.pbxproj, prepare_osx_build_environment.sh, prepare_win_build_environment.ps1
=> Replace EstonianIDCard with libdigidocpp and update openssl to 1.0.2l

src/crypto/Connect.h, src/crypto/TS.cpp
=> Parse Time-Stamp service response status

src/crypto/Connect.cpp
=> Fix build with gcc-7

.travis.yml, prepare_osx_build_environment.sh
=> Increase OSX deployment target

src/crypto/WinSigner.cpp
=> Fix WinSigner PIN parameter and implement with CAPI backend

src/Conf.cpp, src/SignatureXAdES_LT.cpp, src/crypto/OCSP.cpp, src/crypto/OCSP.h
=> Take OCSP URL from AIA extension

src/SignatureXAdES_LT.cpp
=> Fix log message

.travis.yml, prepare_osx_build_environment.sh
=> Skip armv7s on travis to optimize build

src/SignatureXAdES_B.cpp
=> Improve compatibility with standard

src/Exception.h, src/SignatureXAdES_B.cpp, src/digidoc-tool.cpp, test/libdigidocpp_boost.cpp
=> Add MimeType check and Exception warning

src/crypto/Digest.cpp, src/crypto/PKCS11Signer.cpp, src/crypto/WinSigner.cpp
=> Implement signing with ECDSA token

CMakeLists.txt, RELEASE-NOTES.md
=> Increment version number and add first draft of release notes

src/crypto/WinSigner.cpp, src/crypto/X509Crypto.cpp
=> CNG MS SmartCard Provider is strict with RSA parameters allowed only with RSA  key

src/SignatureXAdES_B.cpp
=> Since GCC 4.9 has working regex

src/CMakeLists.txt
=> Fix xerces 3.2 paths

src/SignatureXAdES_B.cpp
=> VC2013 has working regex

src/crypto/TSL.cpp, src/crypto/TSL.h
=> Don't terminate Service parsing when found TakenOverByType extension

src/xml/AnyType.cpp, test/libdigidocpp_boost.cpp
=> Fix reloading time-mark signature and signing

.travis.yml, prepare_win_build_environment.ps1
=> Fix travis OSX build

src/SiVaContainer.cpp
=> SiVa V2 support

examples/libdigidocpp-android/app/src/main/java/ee/ria/libdigidocpp/MainActivity.java, prepare_osx_build_environment.sh
Warning: This is wasting memory and prevents security hardening
IB-5036
=> Fix android openssl relocations

CMakeLists.txt, RELEASE-NOTES.md, build.ps1
=> Update version number and add release notes

src/SiVaContainer.cpp
=> Check SiVa other values

src/SignatureXAdES_LT.cpp
=> Return first OCSP response when chains are not complete and validation fails

src/util/ZipSerialize.cpp
=> Fix windows build

.travis.yml, src/crypto/OCSP.cpp
"c++ - Loop will run at most once (loop increment never executed)"
=> Fix compiler warning and cleanup

examples/libdigidocpp-android/app/src/main/java/ee/ria/libdigidocpp/MainActivity.java, examples/libdigidocpp-android/build-library.sh, examples/libdigidocpp-ios/build-library.sh, prepare_osx_build_environment.sh, src/CMakeLists.txt
=> Build static libs on android

prepare_osx_build_environment.sh, src/CMakeLists.txt
=> Fix library paths and export variables

src/DDoc.cpp, src/SiVaContainer.cpp, src/xml/SecureDOMParser.cpp
=> More verbose logging

src/crypto/OCSP.cpp
=> Find issuer certificate before OCSP validation to Activate TSL region

src/SiVaContainer.cpp
=> Ignore namespace for DDoc 1.1 and 1.2 compatibility

examples/libdigidocpp-ios/build-library.sh, prepare_osx_build_environment.sh, src/CMakeLists.txt
=> Link xalan msg only when linking static and fix travis builds

src/util/File.cpp
=> snapcraft.io support

src/crypto/PKCS11Signer.cpp
=> Use PKCS11 token filter

src/crypto/OCSP.cpp, src/crypto/OpenSSLHelpers.h, src/crypto/PKCS12Signer.cpp, src/crypto/TS.cpp, src/crypto/X509Cert.cpp
=> Add openssl i2d helper, Use SCOPE and fix memory leak

src/digidoc-tool.rc, src/libdigidocpp.rc
=> Update copyright year

src/crypto/Connect.cpp, src/crypto/Connect.h
=> Optimize TSL loading

CMakeLists.txt, RELEASE-NOTES.md, build.ps1, debian/control
=> Increase version number and add release notes

src/SiVaContainer.cpp, src/crypto/Connect.h
=> Handle SiVa HTTP code 400

src/crypto/TSL.cpp, src/crypto/TSL.h
=> More verbose TSL log messages

src/SignatureXAdES_B.cpp, src/SignatureXAdES_B.h
=> Fix crash when SignerRole element is empty

.travis.yml, examples/CMakeLists.txt, examples/pkcs11sign.cpp, test/CMakeLists.txt
=> Update example to latest API and make part of travis build

README.md, build.ps1, prepare_osx_build_environment.sh, prepare_win_build_environment.ps1
=> Update OpenSSL to 1.0.2o

.travis.yml, src/digidoc-tool.cpp, test/CMakeLists.txt
=> Add log parameters to digidoc-tool

src/xml/SecureDOMParser.cpp
=> Restore verbose log messages in exception

.travis.yml
=> Build with OpenSSL 1.1

src/CMakeLists.txt, src/Exception.cpp, src/Exception.h, src/Exports.h
=> Fix Windows linking warnings LNK4049

src/crypto/TS.cpp
=> Enable TS nonce validation

libdigidocpp.i, src/ASiC_E.cpp, src/SignatureTST.cpp, src/crypto/TSL.cpp, src/crypto/WinSigner.cpp, src/crypto/X509Crypto.cpp, src/util/DateTime.cpp
=> Fix some compiler warnings

etc/Doxyfile.in, src/crypto/X509Cert.cpp
=> Fix doxygen warnings

src/DataFile.cpp, src/DataFile_p.h, src/crypto/Digest.cpp, src/crypto/Digest.h, src/crypto/TSL.cpp, src/xml/SecureDOMParser.cpp
=> Use size_t to fix compiler warning and cleanup code

libdigidocpp.i, src/DDoc.cpp, src/DDoc.h, src/Signature.cpp, src/Signature.h, src/SignatureXAdES_LT.cpp, src/SignatureXAdES_LT.h, src/SignatureXAdES_T.cpp, src/SignatureXAdES_T.h, src/crypto/TS.cpp, src/crypto/TS.h, src/digidoc-tool.cpp
=> Message Imprint value

libdigidocpp.i
=> Add option to initialize TSL with parameters

src/util/DateTime.cpp
=> Use thread safe POSIX alternative

src/util/File.cpp
=> Use std::isalnum

src/SiVaContainer.cpp
=> Don't assert when there is not signatures json element

src/crypto/TS.cpp
=> Fix crash when TS_TST_INFO is missing

src/SignatureXAdES_B.cpp, src/SignatureXAdES_LTA.cpp, src/crypto/TSL.cpp
=> Fix memory leaks

src/CMakeLists.txt
=> Merge some conditions

src/crypto/Connect.cpp
=> Workaround OpenSSL crash some rare conditions

src/CMakeLists.txt
=> Fix embded lib and fix clang warning

src/crypto/OpenSSLHelpers.h, src/crypto/TS.cpp, src/crypto/X509CertStore.cpp, src/crypto/X509CertStore.h
=> Fix OpenSSL 1.1 warnings and modernize code

src/CMakeLists.txt
=> Use set_properties and don’t pollute global defines

.travis.yml, RELEASE-NOTES.md
=> Update release notes

test/CMakeLists.txt
=> Add option to set test result format

prepare_osx_build_environment.sh
=> Fix iOS build with Xcode 10

.travis.yml, CMakeLists.txt, debian/control, debian/libdigidocpp-dev.lintian-overrides, debian/libdigidocpp-dev.triggers, src/Container.cpp
=> Add ubuntu 18.10 and fix build and lintian error

src/SignatureXAdES_B.cpp
=> Reset buffer after setting SignatureValue

src/crypto/OCSP.cpp, src/crypto/OCSP.h
=> Use Connect for OCSP connection

src/crypto/X509Crypto.cpp, src/crypto/X509Crypto.h
=> Fix signature verify with OpenSSL 1.1

src/Conf.cpp, src/Conf.h, src/DDoc.cpp, src/PDF.cpp, src/SignatureXAdES_LT.cpp, src/SignatureXAdES_LT.h, src/XmlConf.cpp, src/XmlConf.h, src/crypto/OCSP.cpp, src/crypto/OCSP.h, test/libdigidocpp_boost.cpp, test/test.h
=> Check OCSP TM OID

src/XmlConf.cpp, src/XmlConf.h
=> Set TSA URL

CMakeLists.txt, src/Exception.h, src/SignatureCAdES_T.cpp, src/SignatureCAdES_T.h, src/SignatureTST.cpp, src/SignatureXAdES_LTA.cpp, src/SignatureXAdES_LTA.h, src/SignatureXAdES_T.cpp, src/SignatureXAdES_T.h, src/crypto/TS.cpp, src/crypto/TS.h
=> Handle TSA error code 429 and cleanup some code

src/SiVaContainer.cpp, src/crypto/X509CertStore.cpp
=> Special treatment for E-Seals

.travis.yml
=> Upload artifacts to AWS

RELEASE-NOTES.md, build.ps1, src/Exports.h
=> Update release notes and fix build with recent VisualStudio

libdigidocpp.i, src/XmlConf.cpp, src/XmlConf.h
=> Add XmlConf* instance methods and set XmlConf schema path

src/ASiC_E.cpp, src/ASiC_E.h, src/util/ZipSerialize.cpp, src/util/ZipSerialize.h
=> Cleanup code and locate zip file properties as case sensitive

src/SiVaContainer.cpp, src/crypto/Connect.cpp, src/crypto/Connect.h, src/crypto/TSL.cpp
=> Don't duplicate buffer when sending data to SiVa

examples/DigiDocCSharp/README.md, libdigidocpp.i
=> Fix C# compile

build.ps1, src/CMakeLists.txt
=> Cleanup linking

patches/README.md, patches/xalan-winproj.patch, prepare_win_build_environment.ps1
=> Enable Dynamic Base on XALAN DLL

src/crypto/WinSigner.cpp, src/crypto/WinSigner.h, src/digidoc-tool.cpp
=> Add to WinSigner option to select certificate by thumbprint

examples/DigiDocCSharp/DigiDocCSharp.csproj, libdigidocpp.i
=> Marshal all C# strings to UTF8

src/crypto/TSL.cpp, src/crypto/TSL.h, src/digidoc-tool.cpp
=> Optimize: Change order of digest checks

prepare_osx_build_environment.sh, prepare_win_build_environment.ps1
=> Update XML Securiy C to 2.0.2

README.md, build.ps1, libdigidocpp.wxs, prepare_win_build_environment.ps1
=> Visual Studio 2017 support

src/ASiC_E.cpp, src/Container.cpp, src/DataFile.cpp, src/Exception.cpp, src/digidoc-tool.1.cmake, src/digidoc-tool.cpp
=> Make text more generic

src/crypto/Connect.cpp, src/crypto/TSL.cpp
=> Accept gzip on HEAD command to match ETag content

src/crypto/TSL.cpp
=> Add missing return statement

examples/libdigidocpp-android/app/src/main/java/ee/ria/libdigidocpp/Conf.java, examples/libdigidocpp-android/app/src/main/java/ee/ria/libdigidocpp/Container.java, examples/libdigidocpp-java/src/ee/ria/libdigidocpp/Conf.java, examples/libdigidocpp-java/src/ee/ria/libdigidocpp/Container.java, examples/libdigidocpp-java/src/ee/ria/libdigidocpp/libdigidocpp.java, libdigidocpp.i
=> Fix memory leaks and add option to transfer Config object to C++ library

src/crypto/WinSigner.cpp
=> Use correct CSP key spec

src/crypto/Signer.cpp
=> Set EN profile on when using setSignatureProductionPlaceV2

prepare_osx_build_environment.sh, prepare_win_build_environment.ps1
=> Upgrade OpenSSL 1.0.2r

.travis.yml
=> Fixes travis script to upload tar.gz

.lgtm.yml, README.md
=> Add LGTM scan results

src/ASiContainer.cpp, src/SignatureCAdES_B.cpp, src/SignatureXAdES_B.cpp, src/SignatureXAdES_B.h, src/util/DateTime.cpp, src/util/DateTime.h, src/util/File.cpp, src/util/File.h, test/libdigidocpp_boost.cpp
=> Fix LGTM warning "Call to gmtime is potentially dangerous" and some clang-tidy warnings

src/SignatureXAdES_B.cpp, src/SignatureXAdES_T.cpp
=> Fix 2 LGTM errors

src/DDoc.cpp, src/DDoc.h, src/DDoc_p.h, src/SignatureXAdES_B.cpp, src/XmlConf.cpp
=> Implement LGTM Recommendations and fix some clang-tidy warnings

src/ASiC_E.cpp, src/ASiContainer.cpp, src/SignatureXAdES_B.cpp, src/XmlConf.cpp, src/crypto/PKCS11Signer.cpp, src/crypto/PKCS12Signer.cpp, src/crypto/X509CertStore.cpp
=> Fix coverity string formating warnings

CMakeLists.txt
=> Update LOTL URL

src/crypto/PKCS11Signer.cpp, src/crypto/PKCS11Signer.h
=> Ignore CA type certificates and code cleanup

src/digidoc-tool.cpp
=> Add TSUrl parameter and merge ToolConfig and Params classes

build.ps1, libdigidocpp.i, src/libdigidocpp.i.h
=> Add some setters to swig interface

src/SignatureXAdES_LTA.cpp, src/XmlConf.cpp, src/crypto/TSL.cpp, src/crypto/TSL.h, src/digidoc-tool.1.cmake, src/digidoc-tool.cpp
=> Fix coverity exception warnings

src/crypto/TSL.cpp
=> Fix coverity warnings

build.ps1, libdigidocpp.wxs, patches/xml-security-c-2.0.1-win.patch, prepare_osx_build_environment.sh, prepare_win_build_environment.ps1, src/CMakeLists.txt
=> OpenSSL 1.1.1c

.travis.yml, CMakeLists.txt, build.ps1
=> Increase version number to 3.14.1

src/crypto/OCSP.cpp, src/crypto/OCSP.h
=> Check OCSP request times

src/libdigidocpp.i.h
=> Add addTSLCert member

.travis.yml, RELEASE-NOTES.md, examples/libdigidocpp-android/build-library.sh, examples/libdigidocpp-ios/build-library.sh, patches/xalan-CMakeLists.txt, prepare_osx_build_environment.sh, prepare_win_build_environment.ps1
=> Update iOS openssl 1.1.1d

src/crypto/Signer.cpp, src/digidoc-tool.cpp
=> Enable EN profile only when Street address is non empty

src/SignatureXAdES_T.cpp
=> Add signing certificate check to signing time

.travis.yml
=> Update documentation from travis

src/SiVaContainer.cpp
IB-5897
Signed-off-by: Hans Niinemäe <hans@raulwalter.com>
=> Siva3 compatibility

src/DDoc.cpp, src/DDoc_p.h
=> Use modern C++ to cleanup some code

.travis.yml, CMakeLists.txt, RELEASE-NOTES.md, build-library.sh, build.ps1, etc/Doxyfile.in, examples/android/app/build.gradle, examples/android/app/src/main/res/layout/activity_main.xml, examples/android/build.gradle, src/Conf.cpp
=> Increase version number and minor improvements

src/Exception.cpp, src/Exception.h, src/SignatureXAdES_LT.cpp
=> Check that OCSP producedAt is later than TimeStamp

RELEASE-NOTES.md, src/digidoc-tool.rc, src/libdigidocpp.rc
=> Update copyright year and changelog

.travis.yml, build-library.sh, examples/android/app/build.gradle, examples/android/build.gradle, prepare_osx_build_environment.sh
=> Add android x86_64 and increas NDK 18b

src/Container.cpp
=> Cleanup container implementations

.travis.yml, README.md, build.ps1, libdigidocpp.wxs, prepare_win_build_environment.ps1
=> Visual Studio 2019

etc/digidocpp.conf.cmake, src/Conf.cpp
=> Cleanup old OCSP references

src/crypto/OCSP.cpp, src/crypto/TS.cpp, src/log.cpp
=> Log time and OCSP producedAt

libdigidocpp.i, src/Container.cpp, src/Container.h, src/crypto/Connect.cpp, src/digidoc-tool.cpp, src/libdigidocpp.i.h, src/log.h
=> Split user-agent and application name handling

src/Exception.cpp, src/Exception.h, src/SiVaContainer.cpp, src/crypto/Connect.cpp, src/log.h
=> Throw NetworkError

prepare_osx_build_environment.sh, prepare_win_build_environment.ps1
=> Update OpenSSL 1.1.1e

.travis.yml, src/crypto/X509Cert.cpp
=> Workaround OpenSSL 1.1.1f issues

src/ASiC_E.cpp
=> Handle exception

libdigidocpp.i, src/ASiC_E.cpp, src/ASiC_E.h, src/ASiC_S.cpp, src/ASiC_S.h, src/ASiContainer.cpp, src/ASiContainer.h, src/Container.cpp, src/Container.h, src/DDoc.cpp, src/DDoc.h, src/DataFile.cpp, src/DataFile_p.h, src/SiVaContainer.cpp, src/SiVaContainer.h, src/SignatureTST.cpp, src/SignatureTST.h, src/digidoc-tool.cpp, test/TSLTests.cpp, test/libdigidocpp_boost.cpp
=> Use unique_ptr on Container::create/open

src/util/File.cpp, src/util/File.h
=> Fix encoding on macOS when LC_ALL is defined

src/util/File.cpp, src/util/File.h
=> Use 64 bit stat on windows

.travis.yml, src/Exception.cpp, src/Exception.h, src/crypto/TS.cpp, src/crypto/TS.h
=> Add TSForbidden error code

.travis.yml, CMakeLists.txt, build.ps1, src/CMakeLists.txt
=> Enable Integrity check

src/SiVaContainer.cpp, src/SiVaContainer.h
=> Implement SiVa V3 changes

examples/ios/libdigidocpp.xcodeproj/project.pbxproj, examples/ios/libdigidocpp/AppDelegate.mm, prepare_osx_build_environment.sh, src/ASiC_E.cpp, src/CMakeLists.txt, src/Container.cpp, src/SiVaContainer.cpp, src/SignatureXAdES_B.cpp, src/SignatureXAdES_LTA.cpp, src/XmlConf.cpp, src/crypto/TSL.cpp, src/xml/SecureDOMParser.h, src/xml/URIResolver.cpp
=> Fix iOS string transforming

src/SiVaContainer.cpp
=> Convert only EMBEDDED_BASE64 to HASHCODE

.travis.yml, src/Container.cpp, src/crypto/PKCS11Signer.cpp, src/util/File.cpp, src/util/ZipSerialize.cpp
=> Fix coverity errors

src/CMakeLists.txt, src/SiVaContainer.cpp, src/SiVaContainer.h
=> Allow save container with SiVa backend

src/crypto/Digest.cpp, src/crypto/Digest.h, src/crypto/OpenSSLHelpers.h, src/crypto/PKCS11Signer.cpp, src/crypto/PKCS12Signer.cpp, src/crypto/WinSigner.cpp, src/crypto/X509Crypto.cpp, src/crypto/pkcs11.h, src/digidoc-tool.cpp, test/libdigidocpp_boost.cpp
=> Add PSS signature support

src/PDF.cpp, src/PDF.h
=> Update API to fIx build

src/SignatureXAdES_B.cpp, src/SignatureXAdES_B.h
=> Use first certificate as signer certificate

CMakeLists.txt, src/CMakeLists.txt
=> Disable INTERPROCEDURAL_OPTIMIZATION

.github/workflows/build.yml, prepare_osx_build_environment.sh
=> Don't upload to AWS

src/SignatureXAdES_B.cpp, src/SignatureXAdES_B.h, src/SignatureXAdES_T.cpp, src/SignatureXAdES_T.h
=> Add canonicalization algorithm to time-stamp

src/SignatureXAdES_B.cpp
=> Take first X509CertificateType object

.github/workflows/build.yml, test/data/EE_T-CA-invalid-type.xml, test/data/EE_T-CA-withdrawn-granted-before.xml, test/data/EE_T-CA-withdrawn-granted-later.xml, test/data/EE_T-CA-withdrawn.xml, test/data/EE_T-OCSP-invalid-type.xml, test/data/EE_T-OCSP-withdrawn-granted-before.xml, test/data/EE_T-OCSP-withdrawn-granted-later.xml, test/data/EE_T-OCSP-withdrawn.xml, test/data/EE_T-TSA-invalid-type.xml, test/data/EE_T-TSA-withdrawn-granted-before.xml, test/data/EE_T-TSA-withdrawn-granted-later.xml, test/data/EE_T-TSA-withdrawn.xml, test/data/EE_T-good.xml, test/data/EE_T-no_QCSD.xml, test/data/EE_T-no_QCStatement.xml
=> Add new TSA certificate

build-library.sh, prepare_osx_build_environment.sh, prepare_win_build_environment.ps1
=> Update OpenSSL 1.1.1i

.github/workflows/build.yml, README.md, build.ps1, libdigidocpp.wxs, prepare_win_build_environment.ps1
=> Setup windows build to github actions

CMakeLists.txt, src/CMakeLists.txt, src/digidoc-tool.rc, src/libdigidocpp.rc
=> Update version number

examples/DigiDocCSharp/DigiDocCSharp.csproj, examples/DigiDocCSharp/Program.cs, examples/DigiDocCSharp/README.md
=> Update readme and add "add" command

src/SiVaContainer.cpp
=> Disable HASHCODE DataFile parsing

src/Signature.cpp, src/Signature.h, src/digidoc-tool.cpp
=> Deprecate unused Test type

.github/workflows/build.yml, build-library.sh, prepare_osx_build_environment.sh
=> Build macOS arm64

src/SiVaContainer.cpp, src/SignatureXAdES_B.cpp, src/SignatureXAdES_LTA.cpp, src/crypto/OpenSSLHelpers.h, src/crypto/TSL.cpp
=> Improve compatibility where Xerces-C is configured uint16_t

src/ASiC_E.cpp, src/xml/SecureDOMParser.cpp, src/xml/SecureDOMParser.h
=> Disable DTD handling on manifest files

src/SiVaContainer.cpp
=> Fix rebase

src/Conf.cpp, src/Conf.h, src/SiVaContainer.cpp, src/XmlConf.cpp, src/XmlConf.h, src/crypto/Connect.cpp, src/crypto/Connect.h, src/crypto/X509Cert.cpp, src/crypto/X509Cert.h, src/crypto/X509CertStore.cpp, src/digidoc-tool.cpp
=> Support multiple service certificates

src/SiVaContainer.cpp, src/SiVaContainer.h
=> Handle timestampCreationTime and ocspResponseCreationTime

src/crypto/OCSP.cpp
=> Hande SHA256 OCSP_CERTID message digests

src/Exception.cpp, src/SiVaContainer.cpp, src/SignatureTST.cpp, src/SignatureTST.h, src/SignatureXAdES_LTA.cpp, src/SignatureXAdES_LTA.h, src/SignatureXAdES_T.cpp
=> Add SHA1 warning to timestamp digest

.github/workflows/build.yml, README.md, etc/digidocpp.conf.cmake, src/CMakeLists.txt, src/Conf.cpp
=> Remove obsolete responder references

src/SignatureXAdES_LT.cpp, src/crypto/X509CertStore.cpp, src/crypto/X509CertStore.h
=> Fetch Issuer certificate from AIA extension when not found from TSL

libdigidocpp.i, src/libdigidocpp.i.h
=> Allow to set multiple service certificates

src/SignatureXAdES_LT.cpp, src/XmlConf.cpp
=> Remove duplicate responder certificate

src/SiVaContainer.cpp
=> Use custom Base64 decoder to workaround invalid DDoc Base64 encodings

libdigidocpp.dox, src/SignatureXAdES_LT.cpp, src/crypto/OCSP.cpp, src/crypto/OCSP.h
=> Remove SK OCSP proxy URL

src/Exception.h, src/crypto/Connect.cpp, src/crypto/OCSP.cpp, src/crypto/OpenSSLHelpers.h, src/crypto/X509CertStore.cpp, src/digidoc-tool.cpp
=> Provide specific exception codes for OpenSSLException

build-library.sh, examples/android/app/build.gradle, examples/android/app/src/main/java/ee/ria/libdigidocpp/MainActivity.java, prepare_osx_build_environment.sh, src/CMakeLists.txt
=> Update android NDK to 21

src/crypto/Connect.cpp, src/crypto/Connect.h
=> Workaround SiVa proxy issue

.github/workflows/build.yml, etc/Doxyfile.in, patches/vcpkg-ports/xml-security-c/portfile.cmake, patches/vcpkg-ports/xml-security-c/vcpkg.json, prepare_osx_build_environment.sh
=> Update xml-security-c to 2.0.4

build-library.sh, examples/android/app/build.gradle, examples/android/app/src/main/AndroidManifest.xml, examples/android/build.gradle, prepare_osx_build_environment.sh
=> Update android NDK to r23b

src/crypto/Connect.cpp, src/crypto/TSL.cpp
=> Use SSL SNI extension

src/crypto/Connect.cpp, src/crypto/Connect.h
=> Fix downloading some TSL lists

src/crypto/Connect.cpp, src/crypto/Connect.h, src/crypto/TSL.cpp, src/crypto/X509CertStore.cpp
=> Handle redirect when Location does not contain host

.github/workflows/build.yml, patches/vcpkg-ports/xml-security-c/portfile.cmake
=> Remove CodeQL builds

src/crypto/Connect.cpp
=> Use HTTP 1.1 and handle Transfer-Encoding

src/crypto/TSL.cpp, src/crypto/TSL.h
=> Try to validate 2 PIVOT lists when signing certificate is not trusted

.github/workflows/build.yml, src/crypto/TSL.cpp, src/crypto/TSL.h
=> Update modified time when ETag check succeeded

.github/workflows/build.yml, src/crypto/OCSP.cpp
=> Trust intermediate certificates in trust store

.github/workflows/build.yml, CMakeLists.txt, RELEASE-NOTES.md, build.ps1, prepare_osx_build_environment.sh
=> Update version number to 3.14.10

.github/workflows/build.yml, src/json.hpp
=> Update nlohmann_json to 3.10.5

.github/workflows/build.yml, src/crypto/Connect.cpp
=> Disable unsafe legacy renegotiation

src/CMakeLists.txt, src/digidoc-tool.cpp, src/util/File.cpp, src/util/File.h
=> Use std::filesystem

.github/workflows/build.yml, src/ASiC_E.cpp, src/ASiC_E.h, src/ASiContainer.cpp, src/ASiContainer.h, src/Container.cpp, src/SiVaContainer.cpp, src/SiVaContainer.h, src/SignatureTST.cpp, src/SignatureTST.h, src/SignatureXAdES_LT.cpp, src/SignatureXAdES_LTA.cpp, src/SignatureXAdES_LTA.h, src/XmlConf.cpp, src/XmlConf.h, src/crypto/Digest.cpp, src/crypto/Digest.h, src/crypto/OCSP.cpp, src/crypto/PKCS11Signer.cpp, src/crypto/PKCS11Signer.h, src/crypto/PKCS12Signer.cpp, src/crypto/PKCS12Signer.h, src/crypto/X509CertStore.cpp, src/crypto/X509CertStore.h, src/util/ZipSerialize.cpp, src/util/ZipSerialize.h, test/libdigidocpp_boost.cpp
=> Fix memory leaks reported by unittests 

src/crypto/TS.cpp, src/crypto/X509CertStore.cpp, src/crypto/X509CertStore.h
=> Activate subject and issuer TSL

src/ASiC_E.cpp, src/SignatureXAdES_B.cpp, src/SignatureXAdES_B.h, src/SignatureXAdES_LT.cpp, src/SignatureXAdES_LT.h, src/SignatureXAdES_LTA.cpp, src/SignatureXAdES_T.cpp
=> Improve opening containers with many signatures

src/ASiC_E.cpp, src/SignatureXAdES_B.cpp, src/SignatureXAdES_B.h, src/SignatureXAdES_LT.cpp, src/SignatureXAdES_LT.h, src/SignatureXAdES_LTA.cpp, src/SignatureXAdES_T.cpp
Reverts open-eid/libdigidocpp#446
=> Revert "Improve opening containers with many signatures"

src/crypto/X509CertStore.cpp
=> Make sure that TSL-s are loaded

.github/workflows/build.yml, examples/android/app/build.gradle, examples/android/build.gradle, examples/android/gradle/wrapper/gradle-wrapper.properties, examples/ios/libdigidocpp.xcodeproj/project.pbxproj, prepare_osx_build_environment.sh, src/CMakeLists.txt, test/CMakeLists.txt
=> Update libraries and SDK-s

src/Exports.h, src/crypto/PKCS11Signer.cpp, src/crypto/PKCS11Signer.h, src/crypto/Signer.h, src/crypto/WinSigner.cpp, src/crypto/WinSigner.h
=> Prefer PSS padding with RSA key

src/digidoc-tool.cpp, src/libdigidocpp.i.h
=> When OCSP issuers are not set use base class config, match code with digidoc-tool

src/Conf.h, src/crypto/TSL.cpp, src/crypto/TSL.h, src/crypto/X509CertStore.cpp, src/digidoc-tool.cpp, src/util/File.cpp, src/util/File.h
=> Fix expired TSL handling

README.md, src/util/File.cpp
=> Use correct TMP dir on macOS

.github/workflows/build.yml, build-library.sh, examples/android/app/build.gradle, examples/android/app/src/main/java/ee/ria/libdigidocpp/MainActivity.java, examples/android/build.gradle, examples/ios/libdigidocpp.xcodeproj/project.pbxproj, examples/ios/libdigidocpp/Info.plist, examples/ios/libdigidocpp/MasterViewController.mm, examples/ios/libdigidocpp/libdigidocpp.entitlements, prepare_osx_build_environment.sh
=> Upload Android/iOS artifacts

libdigidocpp.dox, src/XmlConf.cpp, src/XmlConf.h, src/libdigidocpp.i.h, test/CMakeLists.txt, test/libdigidocpp_boost.cpp
=> Add option to save SiVa URL to xml config

.github/workflows/build.yml, CMakeLists.txt, RELEASE-NOTES.md, build.ps1, src/digidoc-tool.cpp
=> Fix digidoc-tool file extraction

src/SignatureXAdES_B.cpp, src/SignatureXAdES_B.h, src/SignatureXAdES_T.cpp
=> Implement CompleteCertificateRefs check

.github/workflows/build.yml, src/Signature.cpp, src/SignatureTST.cpp, src/SignatureXAdES_B.cpp, src/SignatureXAdES_B.h, src/SignatureXAdES_LT.cpp, src/SignatureXAdES_LTA.cpp, src/SignatureXAdES_T.cpp, src/SignatureXAdES_T.h, src/crypto/OCSP.cpp, src/crypto/OCSP.h, src/crypto/PKCS11Signer.cpp, src/crypto/PKCS11Signer.h, src/crypto/PKCS12Signer.cpp, src/crypto/PKCS12Signer.h, src/crypto/Signer.cpp, src/crypto/Signer.h, src/crypto/TS.cpp, src/crypto/TS.h, src/crypto/TSL.cpp, src/crypto/X509Cert.cpp, src/crypto/X509CertStore.cpp, src/crypto/X509Crypto.cpp, src/util/DateTime.cpp, src/util/DateTime.h, test/libdigidocpp_boost.cpp
=> Fix CodeQL quality warnings

build-library.sh, prepare_osx_build_environment.sh
=> Update OpenSSL 1.1.1t

build-library.sh, examples/android/app/build.gradle, examples/android/app/src/main/java/ee/ria/libdigidocpp/MainActivity.java, examples/android/build.gradle, prepare_osx_build_environment.sh, src/util/File.cpp, src/util/File.h
=> Use HOME on Android and build openssl with stdio 

.github/workflows/build.yml, src/crypto/X509CertStore.cpp, src/crypto/X509CertStore.h
=> OpenSSL init / deninit are obsolete

src/DataFile.cpp, src/DataFile_p.h, src/SignatureTST.cpp, src/SignatureXAdES_T.cpp, src/crypto/TS.cpp, src/crypto/TS.h
=> Clear previous OpenSSL errors

libdigidocpp.dox, src/crypto/Digest.cpp, src/crypto/Digest.h, src/crypto/PKCS11Signer.cpp, src/crypto/Signer.cpp, src/crypto/WinSigner.cpp, src/digidoc-tool.1.cmake, src/digidoc-tool.cpp, test/libdigidocpp_boost.cpp
=> Fix RSA padding selection

src/util/File.cpp
=> Workaround for windows service execution

.github/workflows/build.yml, CONTRIBUTING.md, etc/Doxyfile.in, examples/android/app/src/main/AndroidManifest.xml, examples/android/app/src/main/java/ee/ria/libdigidocpp/MainActivity.java, examples/android/build.gradle, examples/android/gradle.properties, examples/android/gradle/wrapper/gradle-wrapper.properties, src/CMakeLists.txt
=> Don't use symlink and update some files/projects

CMakeLists.txt, README.md, build-library.sh, build.ps1, examples/ios/libdigidocpp.xcodeproj/project.pbxproj, examples/ios/libdigidocpp/Base.lproj/Main.storyboard, examples/ios/libdigidocpp/MasterViewController.mm, prepare_osx_build_environment.sh
- add arm64 support to iOS simulator
IB-7723, IB-7745
=> Increase version number

src/ASiC_E.cpp, src/ASiC_E.h, src/ASiC_S.cpp, src/SiVaContainer.cpp, src/SignatureXAdES_B.cpp, src/SignatureXAdES_B.h, src/SignatureXAdES_LT.cpp, src/SignatureXAdES_LT.h, src/SignatureXAdES_LTA.cpp, src/SignatureXAdES_T.cpp, src/digidoc-tool.cpp, src/util/File.cpp, src/util/File.h, src/xml/SecureDOMParser.cpp, src/xml/SecureDOMParser.h
=> Support multiple signatures in single XML

.github/workflows/build.yml, CMakeLists.txt, build.ps1, debian/copyright, src/digidoc-tool.rc, src/libdigidocpp.rc, vcpkg.json
=> Update copyright year and version number

src/SignatureXAdES_B.cpp, src/SignatureXAdES_B.h
=> Add Transforms to SignedProperties reference to specify C14N method

src/crypto/Connect.cpp
=> Fix socket wait with OpenSSL 3.0.14

src/SignatureXAdES_B.cpp, src/SignatureXAdES_B.h
=> Allow to remove signatures on single XML

src/CMakeLists.txt, src/crypto/Connect.cpp, src/crypto/Connect.h, src/crypto/TSL.cpp, src/crypto/TSL.h
=> HTTP headers should be compared case-insensitive

src/crypto/Connect.cpp
=> Retry only when timeout is defined

COPYING, RELEASE-NOTES.md, build.ps1, libdigidocpp.wxs, src/CMakeLists.txt, vcpkg.json
=> Update release notes and code signature timestamping URL-s

src/DataFile.cpp, src/DataFile_p.h, src/SiVaContainer.cpp, src/SignatureTST.cpp, src/SignatureXAdES_B.cpp, src/SignatureXAdES_LTA.cpp, src/SignatureXAdES_LTA.h, src/SignatureXAdES_T.cpp, src/SignatureXAdES_T.h, src/XMLDocument.h, src/crypto/Digest.cpp, src/crypto/Digest.h, src/crypto/TSL.cpp, test/libdigidocpp_boost.cpp
=> Make digest to movable object cleanup usage

examples/DigiDocCSharp/DigiDocCSharp.csproj, examples/DigiDocCSharp/Program.cs, examples/java/gradle/wrapper/gradle-wrapper.properties, examples/java/src/main/java/ee/ria/libdigidocpp/libdigidocpp.java, libdigidocpp.dox, libdigidocpp.i, src/ASiC_E.cpp, src/Signature.cpp, src/Signature.h, src/SignatureXAdES_LT.cpp, src/SignatureXAdES_LT.h, src/SignatureXAdES_LTA.cpp, src/SignatureXAdES_LTA.h, src/SignatureXAdES_T.cpp, src/SignatureXAdES_T.h, src/crypto/Connect.cpp, src/crypto/Connect.h, src/crypto/OCSP.cpp, src/crypto/OCSP.h, src/crypto/OpenSSLHelpers.h, src/crypto/Signer.cpp, src/crypto/Signer.h, src/crypto/TS.cpp, src/crypto/TS.h, src/crypto/X509Cert.cpp, src/digidoc-tool.1.cmake, src/digidoc-tool.cpp, src/libdigidocpp.i.h, test/libdigidocpp_boost.cpp
=> Allow to specify User-Agent info

src/SignatureXAdES_B.cpp, src/XMLDocument.h, src/util/algorithm.h
=> Don't remove whitespace from xml text element

src/util/DateTime.cpp
=> Return empty string when date is null

src/crypto/TSL.cpp, src/crypto/TSL.h
=> Add GR to EL mapping for TSL

libdigidocpp.i, src/crypto/Connect.cpp
=> Fix C# build

.github/workflows/build.yml
No functional changes..
Signed-off-by: Priit Laes <plaes@plaes.org>
=> actions: Add Fedora 42

.github/workflows/build.yml, CMakeLists.txt, RELEASE-NOTES.md, prepare_osx_build_environment.sh, src/CMakeLists.txt, src/util/File.cpp
=> Add release notes

src/XMLDocument.h
=> Use xmlNodeAddContentLen, does not process input text
